spring:
  cloud:
    config:
      profile: dev
      label: master
      uri: http://admin:123456@localhost:5588/
  application:
    name: service-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
server:
  port: 5590
management:
  endpoints:
    web:
      exposure:
        include: "*"
