server:
  port: 5588

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yungby/configserver.git #配置Git仓库位置。
          searchPaths: config-repo #配置仓库路径下的相对搜索位置，可以配置多个。
          username: yungby  #访问 Git 仓库的用户名。
          password: yungby1989 #访问 Git 仓库的用户密码。
          label: master #配置仓库的分支
          ###如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写。

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #配置服务注册中心
