server:
  port: 5592
spring:
  application:
    name: service-turbine
  security:
    user:
      name: admin
      password: 123456
turbine:
  aggregator:
    cluster-config: default
  app-config: config-client,config-server,eureka-server,service-admin,service-turbine,service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
